% This file was generated by Claude from prompt input from Ronan.

% Original prompt: Would you help me put together a simple matlab script
% that plots a square with dimensions 120 x 120 centered about the point
% (0,0), a rectangle with dimensions 31 x 50 located 35 above the bottom
% edge of the square and 29 left of the origin, and a trapezoid whose
% dimensions are measured relative to the center of the rectangle. The
% trapezoid vertices relative to an origin centered at the center of the
% rectangle would be (-120,220), (120, 220), (-170,-200), (170, 200). For
% all these shapes the plots should just show the edges of the shape, not a
% filled shape. The square should be black and relatively thick. The
% rectangle should be black and a little thinner. The trapezoid should be
% green and the same thickness as the rectangle.
% Follow-up: The rectangle's left edge should be 29 from the center of the
% square.

clear; clc; close all;

%% Square: 120 x 120, centered at (0,0)
sqSide = 120;
sqX = [-1  1  1 -1 -1] * sqSide/2;
sqY = [-1 -1  1  1 -1] * sqSide/2;

%% Rectangle: 31 wide x 50 tall
rectW = 31;
rectH = 50;
rectBottom = -sqSide/2 + 35;   % bottom edge 35 above the square's bottom edge
rectLeft   = -29;              % left edge 29 left of the square's center
rectRight  = rectLeft + rectW;
rectTop    = rectBottom + rectH;

rectX = [rectLeft rectRight rectRight rectLeft  rectLeft];
rectY = [rectBottom rectBottom rectTop rectTop rectBottom];

% Center of the rectangle (origin for the trapezoid)
rectCx = (rectLeft + rectRight)/2;
rectCy = (rectBottom + rectTop)/2;

%% Trapezoid: vertices relative to the rectangle center
% Ordered around the perimeter, repeated first point to close the shape
trapLocal = [ -17 -20;
               17 -20;
               12  22;
              -12  22;
              -17 -20 ];
trapX = trapLocal(:,1) + rectCx;
trapY = trapLocal(:,2) + rectCy;

%% Plot
figure; hold on;
plot(sqX,   sqY,   'k', 'LineWidth', 3, DisplayName="Wind Tunnel Cross Section");
plot(rectX, rectY, 'k', 'LineWidth', 1.5, DisplayName="Calibration Target");
plot(trapX, trapY, 'g', 'LineWidth', 1.5, DisplayName="'Good' Vector Region");

axis equal;
grid on;
xlabel('x'); ylabel('y');
title('FoV placement in WT section');
set(gca, FontSize=16)
xlim([min(sqX) max(sqX)])
ylim([min(sqY) max(sqY)])
legend()
hold off;