set MATLAB=C:\Program Files\MATLAB\R2017a
"C:\PROGRA~1\MATLAB\R2017a\bin\win64\gmake" -f CPS_pitch_passive_no_inertia_correction_frequency_04092019.mk  ISPROTECTINGMODEL=NOTPROTECTING EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=0"
